# fly.toml app configuration file generated for site-paru on 2025-10-25T02:50:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-paru'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
