# Netlify configuration file
app = "kariri-xoco-web"

[build]
  # Base directory (root of the repository)
  base = "."
  # Build command for React app
  command = "npm run build"
  # Directory to publish (Vite builds to dist/public)
  publish = "dist/public"
  # Netlify Functions directory
  functions = "netlify/functions"

# Environment variables for production
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"

# Redirects and rewrites
[[redirects]]
  # API routes to Netlify Functions
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  # Health check endpoint
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  # SPA fallback for React Router
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/attached_assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
